// Copyright 2024 LY Corporation
//
// LY Corporation licenses this file to you under the Apache License,
// version 2.0 (the "License"); you may not use this file except in compliance
// with the License. You may obtain a copy of the License at:
//
//   https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.

import SwiftUI

struct ErrorMessageView: View {
    @Binding var error: String

    var body: some View {
        ScrollView {
            Text(error)
                .frame(maxWidth: .infinity)
                .padding()
        }
        .frame(maxWidth: .infinity, minHeight: 200, maxHeight: 200)
        .border(.green)
        .padding()

    }
}

#Preview {
    @State var error = """
        This is an error message1 ...
        This is an error message2 ...
        This is an error message3 ...
        This is an error message4 ...
        This is an error message5 ...
        This is an error message6 ...
        This is an error message7 ...
        This is an error message8 ...
        This is an error message9 ...
        This is an error message10 ...
        This is an error message11 ...
        This is an error message12 ...
        This is an error message13 ...
        This is an error message14 ...
        This is an error message15 ...
        This is an error message16 ...
        This is an error message17 ...
        This is an error message18 ...
    """
    return ErrorMessageView(error: $error)
}
